name: update pubspec.yaml

on:
  
  push:
    branches: [ main ]

   
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: update pubspec version through the dart script
        run: |
          echo github.event
          echo ${{ github.event }}
          echo ${{ github.event.push.commit }}
          echo ${{ github.event_name }}
          
