name: update pubspec.yaml

on:
  
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3
          
      - name: update pubspec version through the dart script
        run: |
          echo github.event
          echo ${{ toJson(github.event) }}
          echo ${{ github.event.payload }}
          echo ${{ github.event_name }}
          
